### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by xxczaki** [joe-bell/next-placeholder#3]
I can't get `next-placeholder` to work on my Linux Mint 20 with Node.js 14.15.0 (LTS). When I run `npm run dev`, it shows the following error:

```
error - ./node_modules/detect-libc/lib/detect-libc.js:4:0
Module not found: Can't resolve 'child_process'
null
```

I think this is not a problem with `next-placeholder` itself, but maybe one will know a fix to such issue.

**Comment by joe-bell** [comment]
I actually had something similar happen when I first started building this project, and it was down to not defining `sharp` as an external module, perhaps you could have a similar issue here? Is `sharp` installed? Try adding [this](https://github.com/lovell/sharp/issues/1605#issuecomment-471618118) to your next.js.config?

It's difficult to help without full context though unfortunately. I'd be more than happy to take a look at a reproduction repo/CodeSandbox

**Comment by brandonpittman** [comment]
Same issue here.

**Comment by brandonpittman** [comment]
@joe-bell Having similar issues here.

https://github.com/brandonpittman/next-blog/tree/dev

Can't find "child-process" with npm run dev and can't find "fs" with npm run build.

**Comment by joe-bell** [comment]
Hey @brandonpittman, the problem you're having there is that you're trying to run `getBlurhash` (which is a **build time** function) inside a component

You should only be running this in `getStaticProps` as per the set-up guide:
https://github.com/joe-bell/next-placeholder#blurhash

Alternatively you could call this in a custom node.js script file and run before `next build`

---

@xxczaki this could also be related to your issue, but please provide a full reproduction if you want me to investigate further

**Comment by brandonpittman** [comment]
@joe-bell Thanks for replying. So if I want to use it in a standalone component, I'll need to accept it as a prop and generate the hash in a page's `getStaticProps`?

**Comment by joe-bell** [comment]
I don't see why it wouldn't work, you'll just want to make sure it's heavily cached

**Comment by brandonpittman** [comment]
@joe-bell Guarantee the OP has the same issue as me. I just generated the hash and used the string directly. Didn't really need to be dynamically created every build. Working great. Thanks a bunch!

**Comment by joe-bell** [comment]
No worries @brandonpittman!

Just a heads up there's some breaking changes coming soon, so keep your eyes peeled in the upcoming releases. Hopefully the new approach will be more flexible

**Comment by joe-bell** [comment]
Closing as there's been no update
